### ISSUE TITLE
Buffersize in compression.go

### ISSUE THREAD

**Issue by MrDemeanor** [coip/bitlogistics#8]
In _compression.go_, the Gzip function has a go routine that reads from a buffer, and writes back to that buffer. I noticed that the **buffersize** variable is hard coded to 8. Would there be any benefit to increasing this buffer size, or would it result in too much data for a gopher to effectively process as it accepts data from the encryption gopher's stream?

**Comment by coip** [comment]
If you refer to 
https://github.com/coip/bitlogistics/blob/0654c6b4bdef3df1894cf5a9b2de4d948828076e/compression/compression.go#L9-L10

Youll find the `buffersize` & `chansize` are even set `= 1`!

This is more for observability of the bitlogistics than for performance.

Locally, I have found that `buffersize=32` is a magic number(assuming word-boundary affinity is the explaination but unsure tbh), with more buffer negligibly affecting gopher throughput(logarithmic payoff) and adding to program resource consumption(linear penalty).

**Comment by coip** [comment]
As Im more focused on the rate of consumption than the resolution/size of those discretely consumed chunks, Im going to close this issue out for now.
Thanks for opening this issue though, I have marked it with the `hz` label to lump it with other performance items Ill be backlogging until everything is a `reader`/`writer`.
